---
name: Renovate
on:
  push:
    branches: 
      - never
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.000.00
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'          
